# site settings

title: Shravya Munugala
description: My CV
taglong: My CV
tagshort: 
url: https://shravya29m.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/Shravya29M/shravya29m.github.io

# author settings

author:
  name: Shravya Munugala
  email: shravya29munugala@gmail.com
photo: #

# social media links

social:
  facebook: 
  github: Shravya29M
  instagram: shravyamunugala
  linkedin: shravya-munugala-40b549252
  stackoverflow: 
  twitter: 

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
